export const keywordControl = new Map<string, string>([
  ['capturar', 'catch'],
  ['caso', 'case'],
  ['con', 'with'],
  ['continuar', 'continue'],
  ['crear', 'new'],
  ['desde', 'from'],
  ['elegir', 'switch'],
  ['esperar', 'await'],
  ['exportar', 'export'],
  ['hacer', 'do'],
  ['importar', 'import'],
  ['mientras', 'while'],
  ['para', 'for'],
  ['retornar', 'return'],
  ['sino', 'else'],
  ['osi', 'else if'],
  ['si', 'if'],
  ['constructor', 'constructor'],
  ['eliminar', 'delete'],
  ['extiende', 'extends'],
  ['finalmente', 'finally'],
  ['instanciaDe', 'instanceof'],
  ['intentar', 'try'],
  ['lanzar', 'throw'],
  ['longitud', 'length'],
  ['romper', 'break'],
  ['simbolo', 'symbol'],
  ['subcad', 'substr'],
  ['tipoDe', 'typeof'],
  ['vacio', 'void'],
  ['producir', 'yield'],
])

export const constantLanguage = new Map<string, string>([
  ['falso', 'false'],
  ['nulo', 'null'],
  ['verdadero', 'true'],
  ['indefinido', 'undefined'],
  ['Infinito', 'Infinity'],
  ['NuN', 'NaN'],
  ['ambienteGlobal', 'globalThis'],
  ['esNuN', 'isNaN'],
])

export const variableLanguage = new Map<string, string>([
  ['ambiente', 'this'],
  ['super', 'super'],
])

export const storageType = new Map<string, string>([
  ['asincrono', 'async'],
  ['clase', 'class'],
  ['const', 'const'],
  ['global', 'var'],
  ['var', 'var'],
  ['mut', 'let'],
  ['porDefecto', 'default'],
  // ['obtener', 'get'],
  // ['establecer', 'set'],
  ['funcion', 'function'],
])

export const metaVariable = new Map<string, string>([
  ['de', 'of'],
  ['en', 'in'],
])

export const supportFunction = new Map<string, string>([
  ['consola', 'console'],
  ['depurador', 'debugger'],
  ['establecerTemporizador', 'setTimeout'],
  ['establecerIntervalo', 'setInterval'],
  ['Fecha', 'Date'],
  ['Numero', 'Number'],
  ['Mate', 'Math'],
  ['Arreglo', 'Array'],
  ['Matriz', 'Array'],
  ['Booleano', 'Boolean'],
  ['Cadena', 'String'],
  ['Funcion', 'Function'],
  ['Promesa', 'Promise'],
])

export const promiseMethods = new Map<string, string>([
  ['todos', 'all'],
  ['todosTerminados', 'allSettled'],
  ['cualquiera', 'any'],
  ['capturar', 'catch'],
  ['finalmente', 'finally'],
  ['carrera', 'race'],
  ['rechaza', 'reject'],
  ['resuelve', 'resolve'],
  ['luego', 'then'],
])

export const dateMethods = new Map<string, string>([
  ['obtenerDia', 'getDate'],
  ['obtenerDiaSemana', 'getDay'],
  ['obtenerAnio', 'getFullYear'],
  ['obtenerAño', 'getFullYear'],
  ['obtenerHoras', 'getHours'],
  ['obtenerMilisegundos', 'getMilliseconds'],
  ['obtenerMinutos', 'getMinutes'],
  ['obtenerMes', 'getMonth'],
  ['obtenerSegundos', 'getSeconds'],
  ['obtenerTiempo', 'getTime'],
  ['obtenerDesfaseDeZonaHoraria', 'getTimezoneOffset'],
  ['obtenerDiaUTC', 'getUTCDate'],
  ['obtenerDiaSemanaUTC', 'getUTCDay'],
  ['obtenerAnioUTC', 'getUTCFullYear'],
  ['obtenerAñoUTC', 'getUTCFullYear'],
  ['obtenerHorasUTC', 'getUTCHours'],
  ['obtenerMilisegundosUTC', 'getUTCMilliseconds'],
  ['obtenerMinutosUTC', 'getUTCMinutes'],
  ['obtenerMesUTC', 'getUTCMonth'],
  ['obtenerSegundosUTC', 'getUTCSeconds'],
  ['ahora', 'now'],
  ['analizar', 'parse'],
  ['establecerFecha', 'setDate'],
  ['establecerAnio', 'setFullYear'],
  ['establecerAño', 'setFullYear'],
  ['establecerHoras', 'setHours'],
  ['establecerMilisegundos', 'setMilliseconds'],
  ['establecerMinutos', 'setMinutes'],
  ['establecerMes', 'setMonth'],
  ['establecerSegundos', 'setSeconds'],
  ['establecerTiempo', 'setTime'],
  ['establecerFechaUTC', 'setUTCDate'],
  ['establecerAnioUTC', 'setUTCFullYear'],
  ['establecerAñoUTC', 'setUTCFullYear'],
  ['establecerHorasUTC', 'setUTCHours'],
  ['establecerMilisegundosUTC', 'setUTCMilliseconds'],
  ['establecerMinutosUTC', 'setUTCMinutes'],
  ['establecerMesUTC', 'setUTCMonth'],
  ['establecerSegundosUTC', 'setUTCSeconds'],
  ['aCadenaFecha', 'toDateString'],
  ['aCadenaISO', 'toISOString'],
  ['aJSON', 'toJSON'],
  ['aCadenaFechaLocale', 'toLocaleDateString'],
  ['aCadenaLocale', 'toLocaleString'],
  ['aCadenaTiempoLocale', 'toLocaleTimeString'],
  ['aCadena', 'toString'],
  ['aCadenaTiempo', 'toTimeString'],
  ['aCadenaUTC', 'toUTCString'],
  ['UTC', 'UTC'],
  ['valorDe', 'valueOf'],
])

export const arrayMethods = new Map<string, string>([
  ['posicion', 'at'],
  ['concatenar', 'concat'],
  ['copiarDentro', 'copyWithin'],
  ['entradas', 'entries'],
  ['cada', 'every'],
  ['llenar', 'fill'],
  ['filtrar', 'filter'],
  ['buscar', 'find'],
  ['buscarIndice', 'findIndex'],
  ['buscarUltimo', 'findLast'],
  ['buscarUltimoIndice', 'findLastIndex'],
  ['plano', 'flat'],
  ['planoMapear', 'flatMap'],
  ['paraCada', 'forEach'],
  ['grupo', 'group'],
  ['grupoAMapear', 'groupToMap'],
  ['incluye', 'includes'],
  ['indiceDe', 'indexOf'],
  ['juntar', 'join'],
  ['claves', 'keys'],
  ['ultimoIndiceDe', 'lastIndexOf'],
  ['mapear', 'map'],
  ['sacar', 'pop'],
  ['agregar', 'push'],
  ['reducir', 'reduce'],
  ['reducirDerecha', 'reduceRight'],
  ['reverso', 'reverse'],
  ['sacarPrimero', 'shift'],
  ['rodaja', 'slice'],
  ['algun', 'some'],
  ['ordenar', 'sort'],
  ['empalmar', 'splice'],
  ['aCadenaLocalizada', 'toLocaleString'],
  ['aCadena', 'toString'],
  ['agregarInicio', 'unshift'],
  ['valores', 'values'],
])

export const mathMethods = new Map<string, string>([
  ['absoluto', 'abs'],
  ['arcocoseno', 'acos'],
  ['arcocosenoHiperbolico', 'acosh'],
  ['arcoseno', 'asin'],
  ['arcosenoHiperbolico', 'asinh'],
  ['arcotangente', 'atan'],
  ['arcotangente2', 'atan2'],
  ['arcotangenteHiperbolica', 'atanh'],
  ['raizCubica', 'cbrt'],
  ['redondearHaciaArriba', 'ceil'],
  ['cerosALaIzquierdaEn32Bits', 'clz32'],
  ['coseno', 'cos'],
  ['cosenoHiperbolico', 'cosh'],
  ['exponencial', 'exp'],
  ['exponencialMenos1', 'expm1'],
  ['redondearHaciaAbajo', 'floor'],
  ['redondearAComaFlotante', 'fround'],
  ['hipotenusa', 'hypot'],
  ['multiplicacionEntera', 'imul'],
  ['logaritmo', 'log'],
  ['logaritmoBase10', 'log10'],
  ['logaritmoDe1Mas', 'log1p'],
  ['logaritmoBase2', 'log2'],
  ['maximo', 'max'],
  ['minimo', 'min'],
  ['potencia', 'pow'],
  ['aleatorio', 'random'],
  ['redondear', 'round'],
  ['signo', 'sign'],
  ['seno', 'sin'],
  ['senoHiperbolico', 'sinh'],
  ['raizCuadrada', 'sqrt'],
  ['tangente', 'tan'],
  ['tangenteHiperbolica', 'tanh'],
  ['truncar', 'trunc'],
])

export const numberMethods = new Map<string, string>([
  ['esFinito', 'isFinite'],
  ['esEntero', 'isInteger'],
  ['esEnteroSeguro', 'isSafeInteger'],
  ['interpretarDecimal', 'parseFloat'],
  ['interpretarEntero', 'parseInt'],
  ['aExponencial', 'toExponential'],
  ['fijarDecimales', 'toFixed'],
  ['aCadenaLocalizada', 'toLocaleString'],
  ['aPrecision', 'toPrecision'],
  ['aCadena', 'toString'],
  ['valorDe', 'valueOf'],
])

export const consoleMethods = new Map<string, string>([
  ['afirmar', 'assert'],
  ['limpiar', 'clear'],
  ['contar', 'count'],
  ['reiniciarContador', 'countReset'],
  ['depurar', 'debug'],
  ['listar', 'dir'],
  ['listarXml', 'dirxml'],
  ['error', 'error'],
  ['agrupar', 'group'],
  ['agruparColapsado', 'groupCollapsed'],
  ['finalizarAgrupacion', 'groupEnd'],
  ['info', 'info'],
  ['escribir', 'log'],
  ['perfil', 'profile'],
  ['finalizarPerfil', 'profileEnd'],
  ['tabla', 'table'],
  ['tiempo', 'time'],
  ['finalizarTiempo', 'timeEnd'],
  ['registrarTiempo', 'timeLog'],
  ['marcaDeTiempo', 'timeStamp'],
  ['rastrear', 'trace'],
  ['advertencia', 'warn'],
])

export const stringMethods = new Map<string, string>([
  ['enPosicion', 'at'],
  ['caracterEn', 'charAt'],
  ['codigoDeCaracterEn', 'charCodeAt'],
  ['puntoDeCodigoEn', 'codePointAt'],
  ['concatenar', 'concat'],
  ['terminaCon', 'endsWith'],
  ['desdeCodigoDeCaracter', 'fromCharCode'],
  ['desdePuntoDeCodigo', 'fromCodePoint'],
  ['incluye', 'includes'],
  ['indiceDe', 'indexOf'],
  ['ultimoIndiceDe', 'lastIndexOf'],
  ['compararLocalizada', 'localeCompare'],
  ['coincidir', 'match'],
  ['coincidirTodo', 'matchAll'],
  ['normalizar', 'normalize'],
  ['rellenarAlFinal', 'padEnd'],
  ['rellenarAlComienzo', 'padStart'],
  ['crudo', 'raw'],
  ['repetir', 'repeat'],
  ['reemplazar', 'replace'],
  ['reemplazarTodo', 'replaceAll'],
  ['buscarRegex', 'search'],
  ['recortar', 'slice'],
  ['dividir', 'split'],
  ['comienzaCon', 'startsWith'],
  ['subcadena', 'substring'],
  ['aMinusculasLocalizada', 'toLocaleLowerCase'],
  ['aMayusculasLocalizada', 'toLocaleUpperCase'],
  ['aMinusculas', 'toLowerCase'],
  ['aMayusculas', 'toUpperCase'],
  ['aCadena', 'toString'],
  ['recortarEspacios', 'trim'],
  ['recortarEspaciosAlFinal', 'trimEnd'],
  ['recortarEspaciosAlComienzo', 'trimStart'],
  ['valorDe', 'valueOf'],
])

export const keywords = new Map<string, string>([
  ...keywordControl,
  ...constantLanguage,
  ...variableLanguage,
  ...storageType,
  ...metaVariable,
  ...supportFunction,
  ...promiseMethods,
  ...dateMethods,
  ...arrayMethods,
  ...mathMethods,
  ...numberMethods,
  ...consoleMethods,
  ...stringMethods,
])

function invertMap(map: Map<string, string>): Map<string, string> {
  const invertedMap = new Map<string, string>()
  for (const [key, value] of map.entries()) {
    invertedMap.set(value, key)
  }

  return invertedMap
}

export function getDictionary(reverse = false): Map<string, string> {
  if (reverse) {
    return invertMap(keywords)
  }

  return keywords
}
