// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNotifications: typeof import('./src/components/AppNotifications.vue')['default']
    ExportModuleButton: typeof import('./src/components/shared/ExportModuleButton.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    NavCircleButton: typeof import('./src/components/NavCircleButton.vue')['default']
    OutputIframe: typeof import('./src/components/OutputIframe.vue')['default']
    Playground: typeof import('./src/components/Playground.vue')['default']
    PlaygroundEditor: typeof import('./src/components/PlaygroundEditor.vue')['default']
    PlaygroundOutput: typeof import('./src/components/PlaygroundOutput.vue')['default']
    PlaygroundTestsEditor: typeof import('./src/components/PlaygroundTestsEditor.vue')['default']
  }
}
