import './generate-esjs-syntax.js'
import './generate-esvue-syntax.js'
import './generate-escss-syntax.js'
import './generate-esjs-language-configurations.js'
import './generate-esvue-language-configurations.js'
import './generate-escss-language-configurations.js'
import './generate-esjs-snippets.js'
import './generate-reserved-words-table.js'
