const keywordsVueRef = new Map([
  ['valor', 'value'],
])

const keywordsArray = new Map([
  ['posicion', 'at'],
  ['concatenar', 'concat'],
  ['copiarDentro', 'copyWithin'],
  ['entradas', 'entries'],
  ['cada', 'every'],
  ['llenar', 'fill'],
  ['filtrar', 'filter'],
  ['buscar', 'find'],
  ['buscarIndice', 'findIndex'],
  ['buscarUltimo', 'findLast'],
  ['buscarUltimoIndice', 'findLastIndex'],
  ['plano', 'flat'],
  ['planoMapeo', 'flatMap'],
  ['paraCada', 'forEach'],
  ['grupo', 'group'],
  ['grupoAMapeo', 'groupToMap'],
  ['incluye', 'includes'],
  ['indiceDe', 'indexOf'],
  ['juntar', 'join'],
  ['claves', 'keys'],
  ['ultimoIndiceDe', 'lastIndexOf'],
  ['mapeo', 'map'],
  ['sacar', 'pop'],
  ['agregar', 'push'],
  ['reducir', 'reduce'],
  ['reducirDerecha', 'reduceRight'],
  ['reverso', 'reverse'],
  ['sacarPrimero', 'shift'],
  ['rodaja', 'slice'],
  ['algun', 'some'],
  ['ordenar', 'sort'],
  ['empalmar', 'splice'],
  ['aCadenaLocalizada', 'toLocaleString'],
  ['aCadena', 'toString'],
  ['agregarInicio', 'unshift'],
  ['valores', 'values'],
])

export const keywords = new Map([
  ['Fecha', 'Date'],
  ['NeN', 'isNaN'],
  ['async', 'async'],
  ['capturar', 'catch'],
  ['caso', 'case'],
  ['clase', 'class'],
  ['con', 'with'],
  ['const', 'const'],
  ['constructor', 'constructor'],
  ['continuar', 'continue'],
  ['crear', 'new'],
  ['de', 'of'],
  ['porDefecto', 'default'],
  ['depurador', 'debugger'],
  ['desde', 'from'],
  ['elegir', 'switch'],
  ['eliminar', 'delete'],
  ['esperar', 'await'],
  ['en', 'in'],
  ['establecer', 'set'],
  ['este', 'this'],
  ['exportar', 'export'],
  ['extiende', 'extends'],
  ['falso', 'false'],
  ['finalmente', 'finally'],
  ['funcion', 'function'],
  ['global', 'var'],
  ['hacer', 'do'],
  ['importar', 'import'],
  ['indefinido', 'undefined'],
  ['instanciaDe', 'instanceof'],
  ['intentar', 'try'],
  ['lanzar', 'throw'],
  ['longitud', 'length'],
  ['mientras', 'while'],
  ['nulo', 'null'],
  ['obtener', 'get'],
  ['osi', 'else if'],
  ['para', 'for'],
  ['retornar', 'return'],
  ['romper', 'break'],
  ['si', 'if'],
  ['simbolo', 'symbol'],
  ['sino', 'else'],
  ['super', 'super'],
  ['subcadena', 'substr'],
  ['tipoDe', 'typeof'],
  ['vacio', 'void'],
  ['var', 'let'],
  ['verdadero', 'true'],
  ['yield', 'yield'],
  ...keywordsArray,
  ...keywordsVueRef,
])
