import chalk from 'chalk'

const tiza = {
  reset: chalk.reset,
  negrita: chalk.bold,
  opaco: chalk.dim,
  cursiva: chalk.italic,
  subrayado: chalk.underline,
  sobrelinea: chalk.overline,
  invertido: chalk.inverse,
  invisible: chalk.hidden,
  tachado: chalk.strikethrough,
  visible: chalk.visible,
  negro: chalk.black,
  rojo: chalk.red,
  verde: chalk.green,
  amarillo: chalk.yellow,
  azul: chalk.blue,
  magenta: chalk.magenta,
  cian: chalk.cyan,
  blanco: chalk.white,
  negroBrillo: chalk.blackBright,
  rojoBrillo: chalk.redBright,
  verdeBrillo: chalk.greenBright,
  amarilloBrillo: chalk.yellowBright,
  azulBrillo: chalk.blueBright,
  magentaBrillo: chalk.magentaBright,
  cianBrillo: chalk.cyanBright,
  blancoBrillo: chalk.whiteBright,
  fondoNegro: chalk.bgBlack,
  fondoRojo: chalk.bgRed,
  fondoVerde: chalk.bgGreen,
  fondoAmarillo: chalk.bgYellow,
  fondoAzul: chalk.bgBlue,
  fondoMagenta: chalk.bgMagenta,
  fondoCian: chalk.bgCyan,
  fondoBlanco: chalk.bgWhite,
  fondoNegroBrillo: chalk.bgBlackBright,
  fondoRojoBrillo: chalk.bgRedBright,
  fondoVerdeBrillo: chalk.bgGreenBright,
  fondoAmarilloBrillo: chalk.bgYellowBright,
  fondoAzulBrillo: chalk.bgBlueBright,
  fondoMagentaBrillo: chalk.bgMagentaBright,
  fondoCianBrillo: chalk.bgCyanBright,
  fondoBlancoBrillo: chalk.bgWhiteBright,
}

export default tiza
