import {
  replaceInstanceof,
  replaceObjects,
  replaceObjectStaticMethods,
  replaceObjectStaticProperties,
} from '../utils'

export const report = () => 'Converts Documento methods to JavaScript'

export const methods = new Map<string, string>([
  ['adoptarNodo', 'adoptNode'],
  ['anexar', 'append'],
  ['temasNavegador', 'browsingTopics'],
  ['posicionCursorDesdePunto', 'caretPositionFromPoint'],
  ['crearAtributo', 'createAttribute'],
  ['crearAtributoNS', 'createAttributeNS'],
  ['crearSeccionCDATA', 'createCDATASection'],
  ['crearComentario', 'createComment'],
  ['crearFragmentoDocumento', 'createDocumentFragment'],
  ['crearElemento', 'createElement'],
  ['crearElementoNS', 'createElementNS'],
  ['crearIteradorNodo', 'createNodeIterator'],
  ['crearInstruccionProcesamiento', 'createProcessingInstruction'],
  ['crearRango', 'createRange'],
  ['crearNodoTexto', 'createTextNode'],
  ['crearCaminanteArbol', 'createTreeWalker'],
  ['elementoDesdePunto', 'elementFromPoint'],
  ['elementosDesdePunto', 'elementsFromPoint'],
  ['salirPantallaCompleta', 'exitFullscreen'],
  ['salirImagenEnImagen', 'exitPictureInPicture'],
  ['salirBloqueoPuntero', 'exitPointerLock'],
  ['obtenerAnimaciones', 'getAnimations'],
  ['obtenerElementoPorId', 'getElementById'],
  ['obtenerElementosPorClase', 'getElementsByClassName'],
  ['obtenerElementosPorEtiqueta', 'getElementsByTagName'],
  ['obtenerElementosPorEtiquetaNS', 'getElementsByTagNameNS'],
  ['obtenerSeleccion', 'getSelection'],
  ['tieneAccesoAlmacenamiento', 'hasStorageAccess'],
  ['tieneAccesoCookiesSinParticiones', 'hasUnpartitionedCookieAccess'],
  ['importarNodo', 'importNode'],
  ['mozEstablecerElementoImagen', 'mozSetImageElement'],
  ['anteponer', 'prepend'],
  ['consultarSelector', 'querySelector'],
  ['consultarTodosSelectores', 'querySelectorAll'],
  ['liberarCaptura', 'releaseCapture'],
  ['reemplazarHijos', 'replaceChildren'],
  ['solicitarAccesoAlmacenamiento', 'requestStorageAccess'],
  ['solicitarAccesoAlmacenamientoPara', 'requestStorageAccessFor'],
  ['iniciarTransicionVista', 'startViewTransition'],
  ['crearExpresion', 'createExpression'],
  ['evaluar', 'evaluate'],
  ['cerrar', 'close'],
  ['obtenerElementosPorNombre', 'getElementsByName'],
  ['tieneFoco', 'hasFocus'],
  ['abrir', 'open'],
  ['escribirLinea', 'writeln'],
  ['analizarHTMLInseguro', 'parseHTMLUnsafe'],
])

export const properties = new Map<string, string>([
  ['elementoActivo', 'activeElement'],
  ['hojasEstiloAdoptadas', 'adoptedStyleSheets'],
  ['cuerpo', 'body'],
  ['conjuntoCaracteres', 'characterSet'],
  ['conteoElementosHijos', 'childElementCount'],
  ['hijos', 'children'],
  ['modoCompatibilidad', 'compatMode'],
  ['tipoContenido', 'contentType'],
  ['scriptActual', 'currentScript'],
  ['tipoDocumento', 'doctype'],
  ['elementoDocumento', 'documentElement'],
  ['documentoURI', 'documentURI'],
  ['incrustados', 'embeds'],
  ['politicaCaracteristicas', 'featurePolicy'],
  ['primerElementoHijo', 'firstElementChild'],
  ['fuentes', 'fonts'],
  ['formularios', 'forms'],
  ['directivaFragmento', 'fragmentDirective'],
  ['elementoPantallaCompleta', 'fullscreenElement'],
  ['cabecera', 'head'],
  ['oculto', 'hidden'],
  ['imagenes', 'images'],
  ['implementacion', 'implementation'],
  ['ultimoElementoHijo', 'lastElementChild'],
  ['enlaces', 'links'],
  ['elementoImagenEnImagen', 'pictureInPictureElement'],
  ['imagenEnImagenHabilitado', 'pictureInPictureEnabled'],
  ['complementos', 'plugins'],
  ['elementoBloqueoPuntero', 'pointerLockElement'],
  ['preRenderizado', 'prerendering'],
  ['scripts', 'scripts'],
  ['elementoDesplazamiento', 'scrollingElement'],
  ['hojasEstilo', 'styleSheets'],
  ['lineaTiempo', 'timeline'],
  ['estadoVisibilidad', 'visibilityState'],
  ['cookie', 'cookie'],
  ['vistaPredeterminada', 'defaultView'],
  ['modoDiseño', 'designMode'],
  ['direccion', 'dir'],
  ['pantallaCompletaHabilitada', 'fullscreenEnabled'],
  ['ultimaModificacion', 'lastModified'],
  ['ubicacion', 'location'],
  ['estadoPreparacion', 'readyState'],
  ['referente', 'referrer'],
  ['titulo', 'title'],
  ['URL', 'URL'],
])

export const objects = new Map<string, string>([['Documento', 'Document']])

export function replace() {
  return {
    ...replaceObjectStaticMethods({
      from: 'documento',
      to: 'document',
      methods: methods,
    }),
    ...replaceObjectStaticProperties({
      from: 'documento',
      to: 'document',
      properties,
    }),
    ...replaceInstanceof({
      from: 'Documento',
      to: 'Document',
    }),
    ...replaceObjects({
      objects,
    }),
  }
}
