export const attributeUsages = {
	accept: ['form', 'input'],
	'accept-charset': ['form'],
	accesskey: ['__GLOBAL__'],
	action: ['form'],
	allow: ['iframe'],
	alt: ['area', 'img', 'input'],
	as: ['link'],
	async: ['script'],
	autocapitalize: ['__GLOBAL__'],
	autocomplete: ['form', 'input', 'select', 'textarea'],
	autoplay: ['audio', 'video'],
	background: ['body', 'table', 'td', 'th'],
	bgcolor: [
		'body',
		'col',
		'colgroup',
		'marquee',
		'table',
		'tbody',
		'tfoot',
		'td',
		'th',
		'tr',
	],
	border: ['img', 'object', 'table'],
	capture: ['input'],
	charset: ['meta'],
	checked: ['input'],
	cite: ['blockquote', 'del', 'ins', 'q'],
	class: ['__GLOBAL__'],
	color: ['font', 'hr'],
	cols: ['textarea'],
	colspan: ['td', 'th'],
	content: ['meta'],
	contenteditable: ['__GLOBAL__'],
	controls: ['audio', 'video'],
	coords: ['area'],
	crossorigin: ['audio', 'img', 'link', 'script', 'video'],
	csp: ['iframe'],
	data: ['object'],
	'data-*': ['__GLOBAL__'],
	datetime: ['del', 'ins', 'time'],
	decoding: ['img'],
	default: ['track'],
	defer: ['script'],
	dir: ['__GLOBAL__'],
	dirname: ['input', 'textarea'],
	disabled: [
		'button',
		'fieldset',
		'input',
		'optgroup',
		'option',
		'select',
		'textarea',
	],
	download: ['a', 'area'],
	draggable: ['__GLOBAL__'],
	enctype: ['form'],
	enterkeyhint: ['textarea', 'contenteditable'],
	for: ['label', 'output'],
	form: [
		'button',
		'fieldset',
		'input',
		'label',
		'meter',
		'object',
		'output',
		'progress',
		'select',
		'textarea',
	],
	formaction: ['input', 'button'],
	formenctype: ['button', 'input'],
	formmethod: ['button', 'input'],
	formnovalidate: ['button', 'input'],
	formtarget: ['button', 'input'],
	headers: ['td', 'th'],
	height: ['canvas', 'embed', 'iframe', 'img', 'input', 'object', 'video'],
	hidden: ['__GLOBAL__'],
	high: ['meter'],
	href: ['a', 'area', 'base', 'link'],
	hreflang: ['a', 'link'],
	'http-equiv': ['meta'],
	id: ['__GLOBAL__'],
	integrity: ['link', 'script'],
	inputmode: ['textarea', 'contenteditable'],
	ismap: ['img'],
	itemprop: ['__GLOBAL__'],
	kind: ['track'],
	label: ['optgroup', 'option', 'track'],
	lang: ['__GLOBAL__'],
	loading: ['img', 'iframe'],
	list: ['input'],
	loop: ['audio', 'marquee', 'video'],
	low: ['meter'],
	max: ['input', 'meter', 'progress'],
	maxlength: ['input', 'textarea'],
	minlength: ['input', 'textarea'],
	media: ['a', 'area', 'link', 'source', 'style'],
	method: ['form'],
	min: ['input', 'meter'],
	multiple: ['input', 'select'],
	muted: ['audio', 'video'],
	name: [
		'button',
		'form',
		'fieldset',
		'iframe',
		'input',
		'object',
		'output',
		'select',
		'textarea',
		'map',
		'meta',
		'param',
	],
	novalidate: ['form'],
	open: ['details', 'dialog'],
	optimum: ['meter'],
	pattern: ['input'],
	ping: ['a', 'area'],
	placeholder: ['input', 'textarea'],
	playsinline: ['video'],
	poster: ['video'],
	preload: ['audio', 'video'],
	readonly: ['input', 'textarea'],
	referrerpolicy: ['a', 'area', 'iframe', 'img', 'link', 'script'],
	rel: ['a', 'area', 'link'],
	required: ['input', 'select', 'textarea'],
	reversed: ['ol'],
	role: ['__GLOBAL__'],
	rows: ['textarea'],
	rowspan: ['td', 'th'],
	sandbox: ['iframe'],
	scope: ['th'],
	scoped: ['style'],
	selected: ['option'],
	shape: ['a', 'area'],
	size: ['input', 'select'],
	sizes: ['link', 'img', 'source'],
	slot: ['__GLOBAL__'],
	span: ['col', 'colgroup'],
	spellcheck: ['__GLOBAL__'],
	src: [
		'audio',
		'embed',
		'iframe',
		'img',
		'input',
		'script',
		'source',
		'track',
		'video',
	],
	srcdoc: ['iframe'],
	srclang: ['track'],
	srcset: ['img', 'source'],
	start: ['ol'],
	step: ['input'],
	style: ['__GLOBAL__'],
	tabindex: ['__GLOBAL__'],
	target: ['a', 'area', 'base', 'form'],
	title: ['__GLOBAL__'],
	translate: ['__GLOBAL__'],
	type: [
		'button',
		'input',
		'embed',
		'object',
		'ol',
		'script',
		'source',
		'style',
		'menu',
		'link',
	],
	usemap: ['img', 'input', 'object'],
	value: [
		'button',
		'data',
		'input',
		'li',
		'meter',
		'option',
		'progress',
		'param',
	],
	width: ['canvas', 'embed', 'iframe', 'img', 'input', 'object', 'video'],
	wrap: ['textarea'],
}
