/**
 * CSS pseudo-classes with Spanish translations.
 */
export const cssPseudoClasses = new Map<string, string>([
  // User action
  ['hover', 'encima'],
  ['active', 'activo'],
  ['focus', 'enfoque'],
  ['focus-within', 'enfoque-dentro'],
  ['focus-visible', 'enfoque-visible'],
  ['visited', 'visitado'],
  ['target', 'objetivo'],

  // Input
  ['checked', 'marcado'],
  ['disabled', 'deshabilitado'],
  ['enabled', 'habilitado'],
  ['indeterminate', 'indeterminado'],
  ['invalid', 'invalido'],
  ['valid', 'valido'],
  ['required', 'requerido'],
  ['optional', 'opcional'],
  ['read-only', 'solo-lectura'],
  ['read-write', 'lectura-escritura'],
  ['placeholder-shown', 'marcador-visible'],
  ['default', 'predeterminado'],
  ['in-range', 'en-rango'],
  ['out-of-range', 'fuera-rango'],
  ['autofill', 'autocompletar'],

  // Structural
  ['first-child', 'primer-hijo'],
  ['last-child', 'ultimo-hijo'],
  ['only-child', 'hijo-unico'],
  ['first-of-type', 'primero-de-tipo'],
  ['last-of-type', 'ultimo-de-tipo'],
  ['only-of-type', 'unico-de-tipo'],
  ['nth-child', 'hijo-n'],
  ['nth-last-child', 'ultimo-hijo-n'],
  ['nth-of-type', 'tipo-n'],
  ['nth-last-of-type', 'ultimo-tipo-n'],
  ['empty', 'vacio'],
  ['root', 'raiz'],

  // Language
  ['lang', 'idioma'],
  ['dir', 'direccion'],

  // Link
  ['link', 'enlace'],
  ['any-link', 'cualquier-enlace'],
  ['local-link', 'enlace-local'],

  // Misc
  ['not', 'no'],
  ['is', 'es'],
  ['where', 'donde'],
  ['has', 'tiene'],
  ['scope', 'ambito'],
  ['current', 'actual'],
  ['past', 'pasado'],
  ['future', 'futuro'],
  ['playing', 'reproduciendo'],
  ['paused', 'pausado'],
  ['seeking', 'buscando'],
  ['buffering', 'cargando'],
  ['stalled', 'detenido'],
  ['muted', 'silenciado'],
  ['volume-locked', 'volumen-bloqueado'],
  ['fullscreen', 'pantalla-completa'],
  ['picture-in-picture', 'imagen-en-imagen'],
  ['defined', 'definido'],
  ['host', 'anfitrion'],
  ['host-context', 'contexto-anfitrion'],
  ['modal', 'modal'],
  ['open', 'abierto'],
  ['closed', 'cerrado'],
  ['popover-open', 'emergente-abierto'],
])

/**
 * CSS pseudo-elements with Spanish translations.
 */
export const cssPseudoElements = new Map<string, string>([
  ['before', 'antes'],
  ['after', 'despues'],
  ['first-line', 'primera-linea'],
  ['first-letter', 'primera-letra'],
  ['selection', 'seleccion'],
  ['placeholder', 'marcador'],
  ['marker', 'marcador-lista'],
  ['backdrop', 'fondo-modal'],
  ['cue', 'señal'],
  ['cue-region', 'region-señal'],
  ['slotted', 'ranura'],
  ['part', 'parte'],
  ['file-selector-button', 'boton-selector-archivo'],
  ['highlight', 'resaltado'],
  ['spelling-error', 'error-ortografico'],
  ['grammar-error', 'error-gramatical'],
  ['target-text', 'texto-objetivo'],
])

/**
 * Generate TypeScript code for the pseudo selectors dictionary.
 */
export function generatePseudoCode(): string {
  const classEntries = Array.from(cssPseudoClasses.entries())
    .map(([css, escss]) => `  ['${escss}', '${css}'],`)
    .join('\n')

  const elementEntries = Array.from(cssPseudoElements.entries())
    .map(([css, escss]) => `  ['${escss}', '${css}'],`)
    .join('\n')

  return `import { invertMap } from '@es-js/core/utils'

/**
 * EsCSS to CSS pseudo-classes dictionary.
 * Maps Spanish pseudo-class names to standard CSS pseudo-class names.
 * Auto-generated by escss-generator.
 */
const pseudoClassesDictionary: Map<string, string> = new Map([
${classEntries}
])

/**
 * EsCSS to CSS pseudo-elements dictionary.
 * Maps Spanish pseudo-element names to standard CSS pseudo-element names.
 * Auto-generated by escss-generator.
 */
const pseudoElementsDictionary: Map<string, string> = new Map([
${elementEntries}
])

/**
 * Get the pseudo-classes dictionary.
 * @param inverted - If true, returns CSS -> EsCSS mapping, otherwise EsCSS -> CSS
 */
export function getPseudoClassesDictionary(inverted = false): Map<string, string> {
  if (!inverted) {
    return pseudoClassesDictionary
  }
  return invertMap(pseudoClassesDictionary)
}

/**
 * Get the pseudo-elements dictionary.
 * @param inverted - If true, returns CSS -> EsCSS mapping, otherwise EsCSS -> CSS
 */
export function getPseudoElementsDictionary(inverted = false): Map<string, string> {
  if (!inverted) {
    return pseudoElementsDictionary
  }
  return invertMap(pseudoElementsDictionary)
}

/**
 * List of all CSS pseudo-classes.
 */
export const cssPseudoClassesList = [
${Array.from(cssPseudoClasses.keys())
  .map((p) => `  '${p}',`)
  .join('\n')}
]

/**
 * List of all EsCSS pseudo-classes.
 */
export const escssPseudoClassesList = [
${Array.from(cssPseudoClasses.values())
  .map((p) => `  '${p}',`)
  .join('\n')}
]

/**
 * List of all CSS pseudo-elements.
 */
export const cssPseudoElementsList = [
${Array.from(cssPseudoElements.keys())
  .map((p) => `  '${p}',`)
  .join('\n')}
]

/**
 * List of all EsCSS pseudo-elements.
 */
export const escssPseudoElementsList = [
${Array.from(cssPseudoElements.values())
  .map((p) => `  '${p}',`)
  .join('\n')}
]
`
}
