/**
 * CSS at-rules with Spanish translations.
 */
export const cssAtRules = new Map<string, string>([
  ['media', 'medios'],
  ['keyframes', 'fotogramas'],
  ['import', 'importar'],
  ['font-face', 'fuente-cara'],
  ['supports', 'soporta'],
  ['charset', 'conjunto-caracteres'],
  ['namespace', 'espacio-nombres'],
  ['page', 'pagina'],
  ['layer', 'capa'],
  ['container', 'contenedor'],
  ['property', 'propiedad'],
  ['scope', 'ambito'],
  ['starting-style', 'estilo-inicial'],
])

/**
 * Generate TypeScript code for the at-rules dictionary.
 */
export function generateAtRulesCode(): string {
  const entries = Array.from(cssAtRules.entries())
    .map(([css, escss]) => `  ['${escss}', '${css}'],`)
    .join('\n')

  return `import { invertMap } from '@es-js/core/utils'

/**
 * EsCSS to CSS at-rules dictionary.
 * Maps Spanish at-rule names to standard CSS at-rule names.
 * Auto-generated by escss-generator.
 */
const dictionary: Map<string, string> = new Map([
${entries}
])

/**
 * Get the at-rules dictionary.
 * @param inverted - If true, returns CSS -> EsCSS mapping, otherwise EsCSS -> CSS
 */
let invertedDictionary: Map<string, string> | undefined

export function getDictionary(inverted = false): Map<string, string> {
  if (!inverted) {
    return dictionary
  }
  if (!invertedDictionary) {
    invertedDictionary = invertMap(dictionary)
  }
  return invertedDictionary
}

/**
 * List of all CSS at-rules.
 */
export const cssAtRulesList = [
${Array.from(cssAtRules.keys())
  .map((r) => `  '${r}',`)
  .join('\n')}
]

/**
 * List of all EsCSS at-rules.
 */
export const escssAtRulesList = [
${Array.from(cssAtRules.values())
  .map((r) => `  '${r}',`)
  .join('\n')}
]
`
}
