/**
 * HTML element selectors that should be translated to Spanish.
 * Maps CSS element selectors to their Spanish equivalents.
 */
export const cssElementTranslations = new Map<string, string>([
  // Document structure
  ['html', 'html'],
  ['body', 'cuerpo'],
  ['head', 'cabeza'],
  ['header', 'encabezado'],
  ['footer', 'pie'],
  ['main', 'principal'],
  ['section', 'seccion'],
  ['article', 'articulo'],
  ['aside', 'lateral'],
  ['nav', 'nav'],

  // Headings
  ['h1', 'h1'],
  ['h2', 'h2'],
  ['h3', 'h3'],
  ['h4', 'h4'],
  ['h5', 'h5'],
  ['h6', 'h6'],

  // Text content
  ['p', 'p'],
  ['div', 'div'],
  ['span', 'span'],
  ['a', 'a'],
  ['strong', 'fuerte'],
  ['em', 'enfasis'],
  ['br', 'br'],
  ['hr', 'hr'],
  ['blockquote', 'cita'],
  ['pre', 'pre'],
  ['code', 'codigo'],

  // Lists
  ['ul', 'ul'],
  ['ol', 'ol'],
  ['li', 'li'],
  ['dl', 'dl'],
  ['dt', 'dt'],
  ['dd', 'dd'],

  // Tables
  ['table', 'tabla'],
  ['thead', 'tabla-cabeza'],
  ['tbody', 'tabla-cuerpo'],
  ['tfoot', 'tabla-pie'],
  ['tr', 'tr'],
  ['th', 'th'],
  ['td', 'td'],
  ['caption', 'titulo'],

  // Forms
  ['form', 'formulario'],
  ['input', 'entrada'],
  ['button', 'boton'],
  ['select', 'seleccionar'],
  ['option', 'opcion'],
  ['textarea', 'areadetexto'],
  ['label', 'etiqueta'],
  ['fieldset', 'conjuntocampos'],
  ['legend', 'leyenda'],

  // Media
  ['img', 'img'],
  ['video', 'video'],
  ['audio', 'audio'],
  ['canvas', 'lienzo'],
  ['svg', 'svg'],
  ['figure', 'figura'],
  ['figcaption', 'leyendafigura'],
  ['picture', 'imagen'],
  ['source', 'fuente'],

  // Interactive
  ['details', 'detalles'],
  ['summary', 'resumen'],
  ['dialog', 'dialogo'],

  // Embedded
  ['iframe', 'marco'],
  ['embed', 'incrustar'],
  ['object', 'objeto'],

  // Other
  ['address', 'direccion'],
  ['time', 'tiempo'],
  ['mark', 'marca'],
  ['progress', 'progreso'],
  ['meter', 'medidor'],
  ['output', 'salida'],
])

/**
 * Generate TypeScript code for the selectors dictionary.
 */
export function generateSelectorsCode(): string {
  const entries = Array.from(cssElementTranslations.entries())
    .map(([css, escss]) => `  ['${escss}', '${css}'],`)
    .join('\n')

  return `import { invertMap } from '@es-js/core/utils'

/**
 * EsCSS to CSS element selector dictionary.
 * Maps Spanish element names to standard HTML element names.
 * Auto-generated by escss-generator.
 */
const dictionary: Map<string, string> = new Map([
${entries}
])

/**
 * Get the selectors dictionary.
 * @param inverted - If true, returns CSS -> EsCSS mapping, otherwise EsCSS -> CSS
 */
let invertedDictionary: Map<string, string> | undefined

export function getDictionary(inverted = false): Map<string, string> {
  if (!inverted) {
    return dictionary
  }
  if (!invertedDictionary) {
    invertedDictionary = invertMap(dictionary)
  }
  return invertedDictionary
}
`
}
