name: Test

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.1.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run test
        run: pnpm -r test:run
